### PR TITLE
[WIP] Add AI guide for government

### PR DESCRIPTION
**Pull request by sknep**
Changes proposed in this pull request:
- Add markdown collection of AI Guide for Government content
- Add layouts and includes for AI Guide for Government section
- Add right-side promo to CoE AI page

**The content is still being reviewed and is a DRAFT. Please do not merge yet!**
TODO:

- [x]  check on images everywhere
- [x] consider renaming collection from `_ai_bok` to something else (`_ai_g4g`, `ai_guide_for_gov`, etc)
- [x] add way for the public to submit feedback on the content (Touchpoints form)
- [x] update with final content when ready

[:sunglasses: PREVIEW](https://federalist-e3c31739-2261-4fa1-9eb6-48bf3db55ad6.app.cloud.gov/preview/gsa/centers-of-excellence/add-ai-guide-for-government/coe/ai-guide-for-government/index.html)

### CODE REVIEW

**Review by jonadecker — CHANGES_REQUESTED** [review]
Overall looks really good. We do need some alt love where there are images.

**Comment by jonadecker** [comment]
Should the G4G landing page "provide feedback" link...pop the modal? Have the modal button on the bottom? Something else?

The "How can we" button on iOS Safari (iPhone 12) behavior is kind of unusual...I'm guessing it's size-related? First touch invokes browser chrome and scoots the button up so there's an adequate touch target, second touch invokes the modal. This is less consistently occurring in IOS Chrome but depends on the page length and scroll.

**Comment by jonadecker** [comment]
Your button height to invoke modal is better, it's still a little touchy. I'll do a larger mobile XBT effort to see whether it's worth exploring something like expanding the target area of the anchor vs. just the height alone

**Comment by sknep** [comment]
Just added the last of the content @jonadecker & @daniellegallant. This is ready for the new images to be uploaded [here](https://github.com/GSA/centers-of-excellence/tree/add-ai-guide-for-government/coe/ai-guide-for-government/images) -- if they use the same names, then the image source paths won't even need to be updated!

**Comment by jonadecker** [comment]
@sknep can you throw me a CSV or XLS of the G4G sitemap so I can run it through our accessibility tool? Or just the XML if that isn't readily doable.

**Comment by sknep** [comment]
Would this work? https://federalist-e3c31739-2261-4fa1-9eb6-48bf3db55ad6.app.cloud.gov/preview/gsa/centers-of-excellence/add-ai-guide-for-government/sitemap.xml

**Comment by jonadecker** [comment]
Yes. Just have to clean it up. The tool won't use XML sitemaps unless they are spiderable and federalist previews aren't.

**Review by jonadecker — APPROVED** [review]

**Review by daniellegallant — APPROVED** [review]
👍

**Pull request merged**
